"use client";

import React, { useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { 
  Sparkles, Search, Play, UploadCloud, Zap, 
  BarChart3, Layers, ArrowRight, CheckCircle2, 
  Cpu, ShieldCheck, Lock, Globe, Server, 
  Activity, RefreshCw, Share2, 
  Languages, HelpCircle, Plus, Clock  // ← 加这个
} from "lucide-react";

// --- 语言包配置 ---
const content = {
  en: {
    nav: {
      core: "Core Engine",
      loop: "Feedback Loop",
      solutions: "Solutions",
      pricing: "Pricing",
      faq: "FAQ",
      login: "CONSOLE LOGIN",
    },
    hero: {
      badge: "SELF-OPTIMIZING ENGINE V2.5",
      title_prefix: "The Data-Driven",
      title_suffix: "Content Loop",
      desc: "Not just a generator. Jilo.ai builds a 'Sense-Decide-Execute' closed loop. We use post-performance data to autonomously fine-tune the algorithm for your next video.",
      cta_primary: "Deploy Pipeline",
      stat_capacity: "DAILY CAPACITY",
      stat_status: "MODEL STATUS"
    },
    dashboard: {
      title: "PERFORMANCE_MONITOR",
      live: "LIVE FEEDBACK",
      retention: "AVG. RETENTION RATE",
      signal: "ENGAGEMENT SIGNAL",
      cycle: "ITERATION CYCLE",
      next_update: "NEXT UPDATE SOON"
    },
    core: {
      title: "Intelligent Architecture",
      subtitle: "Decentralized. Multi-Modal. Fully Automated.",
      tabs: ["DISCOVERY", "CREATION", "NETWORK"],
      discovery: {
        title: "Distributed Data Nodes",
        desc: "Global node network capturing real-time trends without IP blocks.",
        code_comment: "// Identify rising topics before peak",
        cards: ["CROSS-PLATFORM", "REAL-TIME", "SEMANTIC"]
      },
      creation: {
        title: "Multi-Modal Generation",
        desc: "Intelligent routing to specific vertical models (Motion/Visuals) based on script type.",
        visuals: "High-Fidelity Visuals",
        motion: "Motion-Optimized Clips"
      },
      network: {
        title: "Matrix Management",
        desc: "Single node supports 50+ accounts. Fingerprint isolation for zero bans."
      }
    },
    loop: {
      tag: "/// CORE_VALUE: CLOSED LOOP",
      title: "Self-Evolving Factory",
      desc: "Traditional tools just publish. Jilo.ai learns. We monitor retention curves and interaction data of every video to parameterize the next generation model.",
      monitor_title: "Multi-Dim Monitoring",
      monitor_desc: "Aggregates views, like ratios, and retention rates.",
      tuning_title: "Auto-Parameter Tuning",
      tuning_desc: "Low retention? AI shortens the hook of the next video."
    },
    solutions: {
      title: "Built for Scale",
      mcn_title: "MCN Agencies",
      mcn_desc: "Manage hundreds of creator accounts via one dashboard. Auto-flag underperforming assets.",
      brand_title: "Enterprise Brands",
      brand_desc: "Brand Safety First. Semantic filters ensure every second of content aligns with brand values.",
      studio_title: "Traffic Studios",
      studio_desc: "Extreme throughput. Rapidly A/B test niches and auto-scale winners."
    },
    pricing: {
      title: "Platform Pricing",
      subtitle: "Scale your compute. Enterprise SLA available.",
      tiers: [
        { name: "Professional", price: "$299", desc: "High-Frequency Creators", features: ["1,000 Videos/mo", "Standard AI Models", "5 Account Matrix", "Basic Feedback"] },
        { name: "Agency Scale", price: "$499", desc: "Agencies / MCN", features: ["5,000 Videos/mo", "Hi-Fi AI Models", "20 Account Matrix", "Real-time Tuning"] },
        { name: "Enterprise", price: "$1,099", desc: "Large Deployment", features: ["Unlimited Generation", "Private Model Fine-tuning", "Unlimited Accounts", "SLA Dedicated Support"] }
      ],
      select: "Select Plan"
    },
    faq: {
      title: "Frequently Asked Questions",
      subtitle: "Everything you need to know about the Jilo.ai infrastructure.",
      items: [
        { q: "How are video credits calculated?", a: "1 successfully generated video = 1 credit. Failed generations do not deduct credits." },
        { q: "Do I own the copyright?", a: "Yes. You own 100% of the commercial rights to the content generated by Jilo.ai." },
        { q: "Do I need to pay for OpenAI/Gemini APIs?", a: "No. Our 'Professional' and 'Agency' plans include all API costs. Enterprise users can bring their own keys." },
        { q: "Is this a desktop app or web-based?", a: "Jilo.ai is a 100% Cloud SaaS. You can access it from Chrome/Safari on Windows, Mac, or Linux." },
        { q: "Do I need proxies or VPNs?", a: "No. Our distributed crawler network handles IP rotation globally. You don't need to configure anything." },
        { q: "Can I upgrade or downgrade anytime?", a: "Yes. Upgrades take effect immediately. Downgrades take effect at the next billing cycle." }
      ]
    },
    footer: {
      slogan: "Automating the future of content creation.",
      copyright: "© 2024 JILO.AI INC. ALL RIGHTS RESERVED."
    }
  },
  zh: {
    nav: {
      core: "核心架构",
      loop: "闭环进化",
      solutions: "解决方案",
      pricing: "价格方案",
      faq: "常见问题",
      login: "进入控制台",
    },
    hero: {
      badge: "自进化引擎 V2.5",
      title_prefix: "数据驱动的",
      title_suffix: "内容闭环",
      desc: "不仅仅是生成工具。Jilo.ai 构建了“感知-决策-执行”的闭环系统。我们根据视频发布后的反馈数据，自动微调算法，让下一条视频表现更好。",
      cta_primary: "部署生产线",
      stat_capacity: "单日产能",
      stat_status: "模型状态"
    },
    dashboard: {
      title: "性能监控_视图",
      live: "实时反馈",
      retention: "平均完播率",
      signal: "互动信号强度",
      cycle: "迭代周期",
      next_update: "即将更新"
    },
    core: {
      title: "智能工业架构",
      subtitle: "去中心化 · 多模态 · 全自动",
      tabs: ["爆款发现", "内容生成", "矩阵分发"],
      discovery: {
        title: "分布式数据节点",
        desc: "全球节点网络，实时捕获平台趋势，规避 IP 封锁风险。",
        code_comment: "// 在峰值前识别上升趋势",
        cards: ["跨平台覆盖", "实时低延迟", "语义过滤"]
      },
      creation: {
        title: "多模态生成引擎",
        desc: "智能路由系统。根据脚本类型（口播/混剪/动画），自动调用垂直优化的生成模型。",
        visuals: "高保真视觉模型",
        motion: "动态剪辑模型"
      },
      network: {
        title: "矩阵集群管理",
        desc: "单节点支持 50+ 账号并发。指纹环境完全隔离，保障账号资产安全。"
      }
    },
    loop: {
      tag: "/// 核心价值: 数据闭环",
      title: "自我进化的内容工厂",
      desc: "传统工具只是生成，Jilo.ai 负责进化。我们监控每一个视频的完播曲线和互动数据，将其转化为优化参数，反哺给生成模型。",
      monitor_title: "多维数据监控",
      monitor_desc: "自动聚合播放量、完播率、互动比等核心指标。",
      tuning_title: "参数自动调优",
      tuning_desc: "完播率低？AI 自动缩短下条视频的开场黄金 3 秒。"
    },
    solutions: {
      title: "为规模化而生",
      mcn_title: "MCN 机构",
      mcn_desc: "一个后台管理数百个创作者账号。自动识别表现不佳的账号并预警，优化资源配置。",
      brand_title: "品牌营销方",
      brand_desc: "品牌安全 (Brand Safety) 第一。智能过滤敏感话题，确保生成的每一秒内容符合品牌调性。",
      studio_title: "流量工作室",
      studio_desc: "追求极致吞吐量。利用数据反馈机制，快速测试不同赛道，并在爆款出现时自动放大投放。"
    },
    pricing: {
      title: "平台定价",
      subtitle: "按需选择算力规模。支持企业级 SLA。",
      tiers: [
        { name: "Professional", price: "$299", desc: "高频创作者", features: ["1,000 视频/月", "标准 AI 模型", "5 账号矩阵", "基础数据反馈"] },
        { name: "Agency Scale", price: "$499", desc: "代运营 / MCN", features: ["5,000 视频/月", "高保真 AI 模型", "20 账号矩阵", "实时数据调优"] },
        { name: "Enterprise", price: "$1,099", desc: "大规模部署", features: ["无限 视频生成", "私有模型微调", "无限 账号矩阵", "SLA 专属支持"] }
      ],
      select: "选择方案"
    },
    faq: {
      title: "常见问题",
      subtitle: "关于 Jilo.ai 架构与部署的详细解答",
      items: [
        { q: "如何计算视频消耗额度？", a: "每成功生成并发布一支视频计为 1 个额度。生成失败或未通过审核的任务不扣费。" },
        { q: "生成的视频版权归谁？", a: "完全归您所有。您可以将生成的视频用于任何商业用途，无需支付额外版税。" },
        { q: "我需要额外支付 OpenAI / Gemini API 费用吗？", a: "不需要。标准版与专业版套餐已包含所有底层 API 成本。Enterprise 用户可选择接入自己的 Key。" },
        { q: "只能在 Windows 电脑上使用吗？", a: "不是。Jilo.ai 是 100% 基于云端的 SaaS 平台。您可以在 Windows、Mac、Linux 甚至 iPad 上通过浏览器访问。" },
        { q: "我需要购买 VPN 或代理吗？", a: "不需要。我们的全球分布式节点内置了企业级代理网络，自动处理 IP 轮询，您无需任何配置。" },
        { q: "可以随时升级或降级吗？", a: "可以。升级套餐立即生效并补差价；降级套餐将在当前计费周期结束后生效。" }
      ]
    },
    footer: {
      slogan: "自动化内容创作的未来。",
      copyright: "© 2024 JILO.AI INC. 保留所有权利."
    }
  }
};

// --- 顶部滚动数据流 (Ticker) ---
const Ticker = () => {
  const signals = [
    { label: "DATA_FEEDBACK", status: "OPTIMIZING", speed: "14ms" },
    { label: "TREND_RADAR", status: "SCANNING", speed: "GLOBAL" },
    { label: "CONTENT_MODEL", status: "LEARNING", speed: "V2.5" },
    { label: "NODE_NETWORK", status: "ACTIVE", speed: "50+" },
  ];

  return (
    <div className="bg-[#05080F] border-b border-white/5 h-8 flex items-center overflow-hidden whitespace-nowrap relative z-50 text-[10px] font-mono">
      <div className="px-4 font-bold text-indigo-500 bg-[#0B0F17] h-full flex items-center border-r border-white/10 z-10">
        SYSTEM METRICS
      </div>
      <motion.div 
        className="flex gap-12 items-center pl-4"
        animate={{ x: [0, -500] }}
        transition={{ repeat: Infinity, duration: 30, ease: "linear" }}
      >
        {[...signals, ...signals, ...signals, ...signals].map((s, i) => (
          <div key={i} className="flex items-center gap-2 text-slate-500">
             <div className="w-1 h-1 bg-emerald-500 rounded-full animate-pulse"></div>
            <span className="text-slate-300 font-bold">{s.label}</span>
            <span className="text-indigo-400">[{s.status}]</span>
            <span className="opacity-50">::{s.speed}</span>
          </div>
        ))}
      </motion.div>
    </div>
  );
};

export default function Home() {
  const [lang, setLang] = useState<'en' | 'zh'>('zh');
  const [activeTab, setActiveTab] = useState(0);
  const t = content[lang];

  return (
    <div className="min-h-screen bg-[#0B0F17] text-slate-300 font-sans selection:bg-indigo-500/30 selection:text-indigo-200 overflow-x-hidden scroll-smooth">
      <Ticker />
      
      {/* --- Navigation --- */}
      <nav className="sticky top-0 z-40 w-full border-b border-white/5 bg-[#0B0F17]/80 backdrop-blur-xl">
        <div className="flex h-16 items-center justify-between px-6 max-w-[1400px] mx-auto">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-indigo-600 rounded flex items-center justify-center shadow-[0_0_15px_rgba(79,70,229,0.4)]">
              <Zap size={18} className="text-white" fill="currentColor" />
            </div>
            <span className="font-bold text-lg text-white tracking-tight">Jilo.ai</span>
          </div>
          
          <div className="hidden lg:flex items-center gap-1 bg-white/5 p-1 rounded-full border border-white/5">
            <Link href="#core" className="px-4 py-1.5 text-xs font-medium text-slate-400 hover:text-white hover:bg-white/5 rounded-full transition-all">{t.nav.core}</Link>
            <Link href="#loop" className="px-4 py-1.5 text-xs font-medium text-slate-400 hover:text-white hover:bg-white/5 rounded-full transition-all">{t.nav.loop}</Link>
            <Link href="#solutions" className="px-4 py-1.5 text-xs font-medium text-slate-400 hover:text-white hover:bg-white/5 rounded-full transition-all">{t.nav.solutions}</Link>
            <Link href="#pricing" className="px-4 py-1.5 text-xs font-medium text-slate-400 hover:text-white hover:bg-white/5 rounded-full transition-all">{t.nav.pricing}</Link>
            <Link href="#faq" className="px-4 py-1.5 text-xs font-medium text-slate-400 hover:text-white hover:bg-white/5 rounded-full transition-all">{t.nav.faq}</Link>
          </div>

          <div className="flex items-center gap-4">
            <button onClick={() => setLang(lang === 'en' ? 'zh' : 'en')} className="flex items-center gap-1 text-xs font-medium text-slate-400 hover:text-white transition-colors">
              <Languages size={14} />
              <span>{lang === 'en' ? 'EN' : '中'}</span>
            </button>

            <Link href="/login" className="text-xs font-bold text-white border border-white/10 bg-white/5 hover:bg-white/10 px-4 py-2 rounded transition-all flex items-center gap-2">
              {t.nav.login} <ArrowRight size={12}/>
            </Link>
          </div>
        </div>
      </nav>

      <main>
        {/* ==================== SCREEN 1: HERO (Optimized Dashboard) ==================== */}
        <section className="relative pt-20 pb-32 border-b border-white/5">
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[60vw] h-[500px] bg-indigo-900/20 blur-[120px] rounded-full pointer-events-none"></div>
          
          <div className="max-w-[1400px] mx-auto px-6 grid lg:grid-cols-12 gap-16 items-center relative z-10">
            <div className="lg:col-span-5 space-y-8">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded border border-indigo-500/30 bg-indigo-500/10 text-indigo-300 text-[10px] font-mono tracking-wider">
                <RefreshCw size={10} className="animate-spin" />
                <span>{t.hero.badge}</span>
              </div>
              <h1 className="text-5xl md:text-7xl font-bold text-white tracking-tight leading-[1.1]">
                {t.hero.title_prefix} <br/>
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 via-white to-indigo-400">
                  {t.hero.title_suffix}
                </span>
              </h1>
              <p className="text-slate-400 text-lg leading-relaxed">
                {t.hero.desc}
              </p>
              
              <div className="flex flex-col sm:flex-row gap-4 pt-4">
                <Link href="/login" className="bg-indigo-600 hover:bg-indigo-500 text-white px-8 py-4 rounded-lg text-sm font-bold flex items-center justify-center gap-2 transition-all shadow-[0_0_30px_rgba(79,70,229,0.3)]">
                  <Play size={16} fill="currentColor"/> {t.hero.cta_primary}
                </Link>
              </div>
            </div>

            {/* 右侧：Dashboard 2.0 (优化版) */}
            <div className="lg:col-span-7">
              <div className="bg-[#0F1219] border border-white/10 rounded-xl overflow-hidden shadow-2xl relative group">
                {/* 顶部栏 */}
                <div className="h-10 bg-[#1A1F2E] border-b border-white/5 flex items-center px-4 justify-between text-[10px] font-mono text-slate-500">
                   <div className="flex gap-4">
                     <span>IP: 192.168.X.X</span>
                     <span>REGION: US-EAST-1</span>
                     <span className="text-emerald-500">CONNECTED</span>
                   </div>
                   <span>SESSION: JILO_ADMIN_882</span>
                </div>

                <div className="grid grid-cols-12 h-[400px]">
                   {/* 左栏：动态任务队列 */}
                   <div className="col-span-4 border-r border-white/5 bg-[#0D111A] p-4 flex flex-col">
                      <div className="text-[10px] font-bold text-slate-400 mb-3 flex justify-between">
                         <span>PROCESSING QUEUE</span>
                         <span>(4/12)</span>
                      </div>
                      <div className="space-y-2">
                         {[1,2,3,4].map(i => (
                           <div key={i} className="bg-white/5 border border-white/5 p-2 rounded hover:border-indigo-500/30 transition-colors">
                              <div className="flex justify-between items-center mb-1">
                                 <span className="text-[10px] text-white font-mono">TASK_#{2024 + i}</span>
                                 <Clock size={10} className="text-indigo-400" />
                              </div>
                              <div className="w-full h-1 bg-slate-800 rounded-full overflow-hidden">
                                 <motion.div 
                                    className="h-full bg-indigo-500"
                                    initial={{ width: "0%" }}
                                    animate={{ width: ["0%", "100%"] }}
                                    transition={{ duration: 2 + i, repeat: Infinity, ease: "linear" }}
                                 />
                              </div>
                              <div className="flex justify-between mt-1 text-[9px] text-slate-500">
                                 <span>Gen-3 Alpha</span>
                                 <span>Rendering...</span>
                              </div>
                           </div>
                         ))}
                      </div>
                   </div>

                   {/* 中栏：雷达扫描 + 数据 */}
                   <div className="col-span-8 p-6 relative bg-[#0B0F17]">
                      {/* 背景网格动画 */}
                      <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:24px_24px] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)]"></div>

                      <div className="relative z-10">
                         <div className="flex justify-between items-start mb-8">
                            <div className="text-sm font-bold text-indigo-400 flex items-center gap-2">
                               <Activity size={16} /> VIRAL PREDICTION ENGINE
                            </div>
                            <div className="text-right">
                               <div className="text-[10px] text-slate-500">CRAWL RATE</div>
                               <div className="text-2xl font-mono font-bold text-white">842<span className="text-sm text-slate-600">/m</span></div>
                            </div>
                         </div>

                         {/* 优化后的扫描雷达区域 */}
                         <div className="h-48 w-full bg-slate-900/50 border border-slate-800 rounded-lg relative overflow-hidden mb-6">
                            {/* 扫描线 */}
                            <motion.div 
                               className="absolute top-0 bottom-0 w-[2px] bg-indigo-500/80 shadow-[0_0_30px_rgba(99,102,241,1)] z-20"
                               animate={{ left: ["0%", "100%"] }}
                               transition={{ duration: 3, repeat: Infinity, ease: "linear" }}
                            />
                            {/* 发现的信号点 */}
                            <div className="absolute top-[30%] left-[20%] w-3 h-3 bg-emerald-500 rounded-full animate-ping"></div>
                            <div className="absolute top-[30%] left-[20%] w-3 h-3 bg-emerald-500 rounded-full"></div>
                            
                            <div className="absolute bottom-2 left-2 text-[9px] font-mono text-white bg-black/80 px-2 py-1 rounded border border-white/10">
                               DETECTED: 14 VIRAL SIGNALS
                            </div>
                         </div>

                         <div className="grid grid-cols-2 gap-4">
                            <div className="p-4 bg-white/5 border border-white/5 rounded-lg">
                               <div className="text-[10px] text-slate-500 mb-1">EST. REVENUE</div>
                               <div className="text-xl font-bold text-white font-mono">$12,450.00</div>
                            </div>
                            <div className="p-4 bg-white/5 border border-white/5 rounded-lg">
                               <div className="text-[10px] text-slate-500 mb-1">AUTO-POSTED</div>
                               <div className="text-xl font-bold text-white font-mono">3,201</div>
                            </div>
                         </div>
                      </div>
                   </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ==================== SCREEN 2: CORE ==================== */}
        <section id="core" className="py-24 border-b border-white/5 bg-[#0B0F17]">
          <div className="max-w-[1400px] mx-auto px-6">
            <div className="mb-12 md:flex justify-between items-end">
              <div>
                <h2 className="text-3xl font-bold text-white mb-2">{t.core.title}</h2>
                <p className="text-slate-400">{t.core.subtitle}</p>
              </div>
              <div className="flex gap-2 mt-4 md:mt-0">
                {t.core.tabs.map((tab, idx) => (
                   <button key={idx} onClick={() => setActiveTab(idx)} className={`px-4 py-2 text-xs font-mono border rounded transition-all ${activeTab === idx ? 'bg-indigo-600 border-indigo-500 text-white' : 'border-white/10 text-slate-500 hover:border-white/30'}`}>
                      {tab}
                   </button>
                ))}
              </div>
            </div>

            <div className="grid lg:grid-cols-12 gap-8">
               <div className="lg:col-span-4 space-y-4">
                  <TechBox icon={<Globe size={16}/>} title={t.core.discovery.title} desc={t.core.discovery.desc} active={activeTab === 0} />
                  <TechBox icon={<Cpu size={16}/>} title={t.core.creation.title} desc={t.core.creation.desc} active={activeTab === 1} />
                  <TechBox icon={<Share2 size={16}/>} title={t.core.network.title} desc={t.core.network.desc} active={activeTab === 2} />
               </div>
               
               <div className="lg:col-span-8 bg-[#0F1219] border border-white/10 rounded-xl p-8 relative overflow-hidden min-h-[400px]">
                  {activeTab === 0 && (
                     <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="relative z-10">
                        <div className="text-xs font-mono text-indigo-400 mb-4">// TREND_ANALYSIS_LOGIC</div>
                        <div className="p-4 bg-black/50 rounded border border-white/5 font-mono text-sm text-slate-300 leading-relaxed">
                           <span className="text-purple-400">function</span> analyzeTrend(signal) {'{'}<br/>
                           &nbsp;&nbsp;<span className="text-slate-500">{t.core.discovery.code_comment}</span><br/>
                           &nbsp;&nbsp;<span className="text-purple-400">if</span> (signal.velocity {'>'} threshold) {'{'}<br/>
                           &nbsp;&nbsp;&nbsp;&nbsp;<span className="text-emerald-400">return</span> "OPPORTUNITY_DETECTED";<br/>
                           &nbsp;&nbsp;{'}'}<br/>
                           &nbsp;&nbsp;<span className="text-purple-400">return</span> "IGNORE";<br/>
                           {'}'}
                        </div>
                     </motion.div>
                  )}
                  {activeTab === 1 && (
                     <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="relative z-10">
                        <h3 className="text-xl font-bold text-white mb-4">{t.core.creation.title}</h3>
                        <div className="space-y-3">
                           <div className="h-2 w-full bg-white/10 rounded-full overflow-hidden">
                              <div className="h-full bg-indigo-500 w-[75%]"></div>
                           </div>
                           <div className="flex justify-between text-[10px] text-slate-500"><span>{t.core.creation.visuals}</span><span>75%</span></div>
                        </div>
                     </motion.div>
                  )}
                  {activeTab === 2 && (
                     <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="relative z-10 text-center pt-12">
                        <Server size={64} className="text-slate-700 mb-4 mx-auto"/>
                        <h3 className="text-lg font-bold text-white">{t.core.network.title}</h3>
                        <p className="text-sm text-slate-500 mt-2 max-w-md mx-auto">{t.core.network.desc}</p>
                     </motion.div>
                  )}
               </div>
            </div>
          </div>
        </section>

        {/* ==================== SCREEN 3: LOOP ==================== */}
        <section id="loop" className="py-24 border-b border-white/5 bg-[#0B0F17] relative overflow-hidden">
           <div className="absolute right-0 top-0 w-1/2 h-full bg-gradient-to-l from-indigo-900/10 to-transparent pointer-events-none"></div>
           <div className="max-w-[1400px] mx-auto px-6 grid lg:grid-cols-2 gap-16 items-center">
              <div>
                 <div className="text-indigo-500 font-bold text-sm mb-2 tracking-widest">{t.loop.tag}</div>
                 <h2 className="text-4xl font-bold text-white mb-6">{t.loop.title}</h2>
                 <p className="text-slate-400 mb-8 leading-relaxed">{t.loop.desc}</p>
                 <div className="space-y-6">
                    <div className="flex gap-4">
                       <div className="w-12 h-12 rounded-full bg-indigo-900/30 flex items-center justify-center border border-indigo-500/30 shrink-0"><BarChart3 className="text-indigo-400" size={20}/></div>
                       <div><h4 className="text-white font-bold">{t.loop.monitor_title}</h4><p className="text-slate-500 text-xs mt-1">{t.loop.monitor_desc}</p></div>
                    </div>
                 </div>
              </div>
              <div className="relative">
                 <div className="aspect-square rounded-full border border-dashed border-slate-700 flex items-center justify-center relative animate-[spin_60s_linear_infinite]">
                    {/* 简化的闭环动画 */}
                    <div className="absolute top-0 left-1/2 w-2 h-2 bg-indigo-500 rounded-full"></div>
                    <div className="absolute bottom-0 left-1/2 w-2 h-2 bg-indigo-500 rounded-full"></div>
                    <div className="absolute left-0 top-1/2 w-2 h-2 bg-indigo-500 rounded-full"></div>
                    <div className="absolute right-0 top-1/2 w-2 h-2 bg-indigo-500 rounded-full"></div>
                 </div>
                 <div className="absolute inset-0 flex items-center justify-center">
                    <div className="text-center">
                       <div className="text-4xl font-bold text-white">+<span className="text-emerald-400">34%</span></div>
                       <div className="text-xs text-slate-500 mt-1">EFFICIENCY</div>
                    </div>
                 </div>
              </div>
           </div>
        </section>

        {/* ==================== SCREEN 4: SOLUTIONS ==================== */}
        <section id="solutions" className="py-24 border-b border-white/5 bg-[#05080F]">
           <div className="max-w-[1400px] mx-auto px-6 text-center">
              <h2 className="text-3xl font-bold text-white mb-16">{t.solutions.title}</h2>
              <div className="grid md:grid-cols-3 gap-8">
                 <SolutionCard icon={<Layers/>} title={t.solutions.mcn_title} desc={t.solutions.mcn_desc} color="indigo"/>
                 <SolutionCard icon={<ShieldCheck/>} title={t.solutions.brand_title} desc={t.solutions.brand_desc} color="purple"/>
                 <SolutionCard icon={<Zap/>} title={t.solutions.studio_title} desc={t.solutions.studio_desc} color="emerald"/>
              </div>
           </div>
        </section>

        {/* ==================== SCREEN 5: PRICING ==================== */}
        <section id="pricing" className="py-24 bg-[#0B0F17] relative">
           <div className="max-w-[1400px] mx-auto px-6 relative z-10">
              <div className="text-center mb-16">
                 <h2 className="text-3xl font-bold text-white mb-4">{t.pricing.title}</h2>
                 <p className="text-slate-400">{t.pricing.subtitle}</p>
              </div>
              <div className="grid lg:grid-cols-3 gap-8 max-w-6xl mx-auto items-end">
                 {t.pricing.tiers.map((plan, i) => (
                    <PricingCard key={i} tier={plan.name} price={plan.price} desc={plan.desc} features={plan.features} highlight={i === 1} btnText={t.pricing.select} />
                 ))}
              </div>
           </div>
        </section>

        {/* ==================== SCREEN 6: FAQ (NEW) ==================== */}
        <section id="faq" className="py-24 border-t border-white/5 bg-[#0B0F17]">
          <div className="max-w-[1200px] mx-auto px-6">
            <div className="text-center mb-16">
              <h2 className="text-3xl font-bold text-white mb-4">{t.faq.title}</h2>
              <p className="text-slate-400">{t.faq.subtitle}</p>
            </div>

            <div className="grid md:grid-cols-2 gap-6">
              {t.faq.items.map((item, i) => (
                <div key={i} className="p-6 bg-white/5 border border-white/5 rounded-xl hover:border-white/10 transition-all">
                  <div className="flex gap-4 items-start">
                    <div className="w-6 h-6 rounded-full bg-indigo-900/30 flex items-center justify-center text-indigo-400 shrink-0 mt-1">
                      <HelpCircle size={14} />
                    </div>
                    <div>
                      <h3 className="text-lg font-bold text-white mb-2 leading-snug">{item.q}</h3>
                      <p className="text-sm text-slate-400 leading-relaxed">
                        {item.a}
                      </p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* --- FOOTER --- */}
        <footer className="bg-black border-t border-white/10 pt-16 pb-8 text-sm text-slate-500">
           <div className="max-w-[1400px] mx-auto px-6 text-center">
              <p className="mb-4">{t.footer.slogan}</p>
              <div>{t.footer.copyright}</div>
           </div>
        </footer>
      </main>
    </div>
  );
}

// --- 子组件 ---
function TechBox({ icon, title, desc, active }: any) {
   return (
      <div className={`flex items-start gap-4 p-4 rounded border transition-all ${active ? 'bg-white/5 border-indigo-500/50' : 'border-transparent opacity-50'}`}>
         <div className={`mt-1 ${active ? 'text-indigo-400' : 'text-slate-600'}`}>{icon}</div>
         <div><div className={`font-bold text-sm ${active ? 'text-white' : 'text-slate-400'}`}>{title}</div><div className="text-xs text-slate-500 mt-1 leading-relaxed">{desc}</div></div>
      </div>
   )
}

function SolutionCard({ icon, title, desc, color }: any) {
  const bgColors: any = { indigo: 'bg-indigo-900/20', purple: 'bg-purple-900/20', emerald: 'bg-emerald-900/20' };
  const textColors: any = { indigo: 'text-indigo-400', purple: 'text-purple-400', emerald: 'text-emerald-400' };
  
  return (
    <div className="p-8 rounded-2xl bg-[#0B0F17] border border-white/5 hover:border-white/10 transition-all group text-left">
       <div className={`w-12 h-12 rounded-lg flex items-center justify-center mb-6 transition-colors ${bgColors[color]} ${textColors[color]}`}>
          {React.cloneElement(icon, { size: 24 })}
       </div>
       <h3 className="text-xl font-bold text-white mb-3">{title}</h3>
       <p className="text-slate-400 text-sm leading-relaxed mb-6">{desc}</p>
    </div>
  )
}

function PricingCard({ tier, price, desc, features, highlight, btnText }: any) {
   return (
      <div className={`p-8 rounded-2xl border transition-all ${highlight ? 'bg-[#0F1623] border-indigo-500 shadow-[0_0_50px_rgba(79,70,229,0.15)] scale-105 z-10' : 'bg-white/5 border-white/10 hover:border-white/20'}`}>
         {highlight && <div className="text-xs font-bold text-indigo-400 mb-2">RECOMMENDED</div>}
         <h3 className="text-xl font-bold text-white">{tier}</h3>
         <p className="text-sm text-slate-500 mb-6">{desc}</p>
         <div className="text-4xl font-bold text-white mb-8">{price}<span className="text-lg text-slate-500 font-normal">/mo</span></div>
         <ul className="space-y-4 text-sm text-slate-300 mb-8">
            {features.map((f: string, i: number) => (
               <li key={i} className="flex gap-3"><CheckCircle2 size={16} className={highlight ? "text-indigo-400" : "text-slate-500"}/> {f}</li>
            ))}
         </ul>
         <Link href="/login" className={`w-full py-4 rounded font-bold transition-all flex items-center justify-center ${highlight ? 'bg-indigo-600 text-white hover:bg-indigo-500' : 'border border-white/20 text-white hover:bg-white/5'}`}>
            {btnText}
         </Link>
      </div>
   )
}